# Generated by Django 3.2.4 on 2021-07-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_remove_feedback_interview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('feedback_text', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
