# Generated by Django 3.2.4 on 2021-07-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_savedfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfeedback',
            name='feedback_score',
            field=models.FloatField(default=0),
        ),
    ]
